# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a44766911585b0bc3e94042cb6b87987869479008f70422d22f2ee4ad9148eee3bef6a6f2a75394720c583e8715df9dfaa1766ae8fef1f20e3848fe27c9d5fe0

test:
  secret_key_base: 1e8af42b69b65228d41f8376a2867dc95132e05d18c172702d8acbefd13745275be6a75000e89e38b3d68c949405fc4a4552b846147555bcc773cf87c488b1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
